<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>



<div class="banner-home__container">
    <?php
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('banner-block')
        ->toHtml();
    ?>
</div>




<?php /* echo $block -> getChildHtml("pippo"); */ ?>

